### ISSUE TITLE
wiki 在Wayback 部分页面已经打不开了，建使用Google网页快照

### ISSUE THREAD

**Issue by Ehco1996** [shadowsocksr-backup/shadowsocksr#1]
* 地址在这里：
<http://webcache.googleusercontent.com/search?q=cache:https://github.com/breakwa11/shadowsocks-rss/wiki/SSR-QRcode-scheme>

希望有心人能将wiki完整的fork一下，方便查看

**Comment by ugvf2009** [comment]
@Ehco1996 已经打不开了，Error 404，完了。这么好的项目都被关了。看来真的是闭关锁国了！大清要回来了

**Comment by jptx1234** [comment]
这里有完整的wiki，且wiki里的链接均已修正，感谢[@Ssrbackup ](https://github.com/Ssrbackup)
https://github.com/Ssrbackup/shadowsocks-rss/wiki

**Comment by Balnea** [comment]
Wiki里面好像找不到关于obfs的相关内容，是不是丢失了？

**Comment by jptx1234** [comment]
https://github.com/shadowsocksr-backup/shadowsocks-rss/blob/master/ssr.md
你指的是不是这个 @Balnea
