### ISSUE TITLE
我至今没搞懂要在linux上运行ssr clinet要安装哪些模块，以及如何进行配置

### ISSUE THREAD

**Issue by Edelwiess** [shadowsocksr-backup/shadowsocksr#11]
这个ssr装好了之后是不是server和clinet一体的？如果要当client用该怎么配置？
Thanks,
Edel

**Comment by ghost** [comment]
Install shadowsocksr just like you install it on the server.
`[user@source:/shadowsocksr/shadowsocks] $ python local.py -c client-config.json`
File client-config.json:
```
{
    "local_port": 1080,
    "timeout": 300,
    "server": "224.17.109.115",
    "server_port": 8848,
    "password": "hxVBJaXUYKMz",
    "method": "aes-256-cfb",
    "protocol": "origin",
    "protocol_param": "",
    "obfs": "plain",
    "obfs_param": ""
}
```
See [HERE](https://github.com/shadowsocksr-backup/shadowsocks-rss/wiki/Python-client-setup-(Mult-language)) for more details.

**Comment by Edelwiess** [comment]
Thx
