### ISSUE TITLE
为何安卓手机端的shadow socksr无法订阅ssr服务器？

### ISSUE THREAD

**Issue by Ouksnack** [shadowsocksr-backup/shadowsocksr#20]
pc端可以订阅ssr服务器并且正常使用，但是我用Android
![098](https://user-images.githubusercontent.com/36025924/37383730-780dd50e-2785-11e8-8818-9e227bf2a5b3.png)
手机无法正常订阅，或者无法连接网络服务器

**Comment by zhchyu2014** [comment]
订阅地址不对，需填写可用的地址
