### ISSUE TITLE
Is this repo still being maintained?!

### ISSUE THREAD

**Issue by setekhid** [shadowsocksr-backup/shadowsocksr#9]
Is this repo still being maintained or already merged into shadowsocks?!

**Comment by baimafeima** [comment]
I am also confused about this entire project. What's the "r" about? Why isn't there any clearer documentation? I'd rather avoid this until there is clear info about it. Also, there is no clear installation instruction whatsoever and confusing terminology. If you want people to use your software, make it simple.

**Comment by jptx1234** [comment]
@baimafeima This project is the backup of "ShadowsocksR".  It is just the backup of the code. The project "ShadowsocksR" has been deleted. If you don't know about ShadowsocksR, please google it. There are many tutorials about it. Nobody will continue to work on this project, except another fork of "shadowsocksr" named "[Shadowsocksrr](https://github.com/shadowsocksrr/shadowsocks-rss)".
Sorry for my poor english.If you are Chinese,please read the following words.
这个项目仅仅是ShadowsocksR的备份而已，原项目已经删了，想要找使用教程的话，谷歌可以出来一大堆，项目早就没人维护了，但是有人开了个新的fork叫“Shadowsocksrr”，继续开发新的特性，这个新的fork相当于一个新项目了。。不过那个新fork也不会提供详细的教程，这种项目是做什么的你也知道，曝光多了那就是必死无疑，那个新的fork作者说了要继续提高shadowsocksrr的使用门槛，只让以前已经懂的人用（这个数量已经够多了），尽力在造福一部分人的同时又控制住使用数量，尽力延长新项目的寿命。如果你想了解shadowsocksr的说明，看这个[wiki](https://github.com/Ssrbackup/shadowsocks-rss/wiki)或者谷歌教程。

**Comment by jptx1234** [comment]
@baimafeima This project is the backup of "ShadowsocksR". It is just the backup of the code. The project "ShadowsocksR" has been deleted. If you don't know about ShadowsocksR, please google it. There are many tutorials about it. If you want to get the new feature, please see another fork of "shadowsocksr" named "[Shadowsocksrr](https://github.com/shadowsocksrr/shadowsocks-rss)".
Sorry for my poor english.If you are Chinese,please read the following words.
这个项目仅仅是ShadowsocksR的备份而已，原项目已经删了，想要找使用教程的话，谷歌可以出来一大堆，这个项目不会有什么新的发展了，但是有人开了个新的fork叫“Shadowsocksrr”，继续开发新的特性，这个新的fork相当于一个新项目了。。不过那个新fork也不会提供详细的教程，这种项目是做什么的你也知道，曝光多了那就是必死无疑，那个新的fork作者说了要继续提高shadowsocksrr的使用门槛，只让以前已经懂的人用（这个数量已经够多了），尽力在造福一部分人的同时又控制住使用数量，尽力延长新项目的寿命。如果你想了解shadowsocksr的说明，看这个[wiki](https://github.com/Ssrbackup/shadowsocks-rss/wiki)或者谷歌教程。

**Comment by setekhid** [comment]
More information would be great, but thx

**Comment by baimafeima** [comment]
@jptx1234 Thanks for the updates but this still makes me wonder why there are separate shadowsocks projects in the first place? If you have new suggestions for features why not talk to the shadowsocks team about it? Shadowsocks urgently needs replacement of `zbar`. Any chance this is replaced in one of your implementations? If yes, could you make a pull request with shadowsocks to fix this? What are the main reasons for not continuing with shadowsocks anyway?
@setekhid Why close this issue when we can clarify more here?

**Comment by jptx1234** [comment]
@baimafeima 下面这段话我不想让国际友人看，我故意以中文说。shadowsocksr的原作者是破娃酱（breakwa11），她在一开始的时候就跟shadowsocks说过她的想法，以及shadowsocks的弱点，但是最后他们的看法不一致，破娃酱就自己维护了这个shadowsocksr。。而且破娃酱的性格一向是特立独行，比较激烈，个人色彩比较多（这些特点也是这个项目这么牛逼的原因之一），不会再向shadowsocks贡献，只维护自己的shadowsocksr，shadowsocksr本来被她闭源了，后来在一堆人怼了她之后开源了。破娃酱一直在从各种角度试图证明原来的shadowsocks有很大的缺陷，试图让大家去用她的shadowsocksr而不是原版shadowsocks，但是双方一直在争执。破娃酱树敌很多，直到删项目。。。。。所以，shadowsocksr合并到shadowsocks是不可能的。。。两个项目之间的差异越来越大，不过现在，shadowsocks也开始有混淆了，也算是shadowsocksr对shadowsocks的影响吧。

**Comment by jptx1234** [comment]
看了之后说一下，我把那段删掉

**Comment by setekhid** [comment]
@baimafeima Cause my question has already been answered. All I want is the obfuscator code. That's the biggest difference between those two projects.

@jptx1234 We got a lot of tunnel solutions, if the communities can combine together, it would be great.
